#!/usr/bin/env node

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = path.dirname(fileURLToPath(import.meta.url));

async function main() {
  const stats = [];

  for (const { absolutePath, relativePath, content } of await findTexFiles("active-recall.tex")) {
    const count = countTopLevelEnumerateItems(content);
    if (count > 0) {
      stats.push({
        absolutePath,
        relativePath,
        title: extractTitle(content),
        count,
      });
    }
  }

  await writeFile(path.join(rootDir, "stats.tex"), renderStatsFile(stats), "utf8");
}

async function findTexFiles(startRelativePath) {
  const ignored = new Set(["active-recall.tex", "_index.tex", "stats.tex"]);
  const visited = new Set();
  const files = [];

  async function visit(relativePath) {
    relativePath = path.normalize(relativePath.endsWith(".tex") ? `${relativePath}` : `${relativePath}.tex`);
    const absolutePath = path.join(rootDir, relativePath);
    if (visited.has(absolutePath)) {
      return;
    }
    visited.add(absolutePath);
    const content = stripComments(await readFile(absolutePath, "utf8"));
    if (!ignored.has(path.basename(absolutePath))) {
      files.push({ absolutePath, relativePath, content });
    }
    for (const inputPath of extractInputPaths(content)) {
      await visit(inputPath);
    }
  }

  await visit(startRelativePath);

  return files;
}

function extractInputPaths(source) {
  return [...source.matchAll(/\\input\{([^}]+)\}/g)].map((match) => match[1].trim()).filter(Boolean);
}

function stripComments(source) {
  return source
    .split("\n")
    .map((line) => {
      let escaped = false;

      for (let index = 0; index < line.length; index += 1) {
        const character = line[index];

        if (character === "%" && !escaped) {
          return line.slice(0, index);
        }

        escaped = character === "\\" && !escaped;

        if (character !== "\\") {
          escaped = false;
        }
      }

      return line;
    })
    .join("\n");
}

function countTopLevelEnumerateItems(source) {
  const environmentStack = [];
  let enumerateDepth = 0;
  let count = 0;

  for (const match of source.matchAll(/\\begin\{(enumerate|itemize)\}|\\end\{(enumerate|itemize)\}|\\item\b/g)) {
    const token = match[0];

    if (token.startsWith("\\begin{")) {
      const environment = match[1];
      environmentStack.push(environment);

      if (environment === "enumerate") {
        enumerateDepth += 1;
      }

      continue;
    }

    if (token.startsWith("\\end{")) {
      const environment = match[2];
      const popped = environmentStack.pop();

      if (environment === "enumerate" && popped === "enumerate") {
        enumerateDepth = Math.max(0, enumerateDepth - 1);
      }

      continue;
    }

    const currentEnvironment = environmentStack.at(-1);

    if (currentEnvironment === "enumerate" && enumerateDepth === 1) {
      count += 1;
    }
  }

  return count;
}

function extractTitle(source) {
  const match = source.match(/\\(?:sub)*section\{([^}]*)\}/);
  return match ? match[1].trim() : "Untitled Topic";
}

function renderStatsFile(stats) {
  const totalQuestions = stats.reduce((sum, entry) => sum + entry.count, 0);
  return [
    `% This file is generated by generate-stats.js. Do not edit manually.`,
    ``,
    `\\section*{Question Statistics}`,
    ``,
    `\\subsection*{Global Statistics}`,
    ``,
    `\\begin{itemize}`,
    `\\item Total topic files counted: ${stats.length}.`,
    `\\item Total questions counted: ${totalQuestions}.`,
    `\\end{itemize}`,
    ``,
    `\\subsection*{Questions by Topic}`,
    ``,
    `\\begin{enumerate}`,
    ...stats.map((entry) => `  \\item ${entry.title}: \\textbf{${entry.count}}`),
    `\\end{enumerate}`,
    ``,
  ].join("\n");
}

await main();
